2019-10-08 08:12:15,399 - file - DEBUG - Reading blob: links.json
2019-10-08 08:12:17,107 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:12:18,867 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:12:19,205 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:14:11,521 - file - DEBUG - Reading blob: links.json
2019-10-08 08:14:13,147 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:14:14,459 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:14:14,810 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:14:15,388 - file - DEBUG - Reading blob: links.json
2019-10-08 08:14:16,811 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:14:19,738 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:14:20,044 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:06,511 - file - DEBUG - Reading blob: links.json
2019-10-08 08:15:08,469 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:15:09,828 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:10,141 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:13,505 - file - DEBUG - Reading blob: links.json
2019-10-08 08:15:14,794 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:15:16,348 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:16,707 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:24,263 - file - DEBUG - Reading blob: links.json
2019-10-08 08:15:26,574 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:15:27,915 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:28,235 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:32,389 - file - DEBUG - Reading blob: links.json
2019-10-08 08:15:33,616 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:15:35,485 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:15:35,786 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:16:26,581 - file - DEBUG - Reading blob: links.json
2019-10-08 08:16:27,761 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:16:29,669 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:16:29,979 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:16:30,270 - flask.app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./main.py", line 189, in renderGraph
    plot_url_sold= graphSold(blob_sold))
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/templates/graph.html", line 5, in top-level template code
    <script src="{{ url_for('app',filename='static/styles/view.js') }}"></script>
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'app' with values ['filename']. Did you mean 'renderGraph' instead?
2019-10-08 08:17:58,066 - file - DEBUG - Reading blob: links.json
2019-10-08 08:17:59,895 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:18:01,981 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:18:02,340 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:18:26,883 - file - DEBUG - Reading blob: links.json
2019-10-08 08:18:28,849 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:18:30,712 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:18:31,012 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:18:31,294 - flask.app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./main.py", line 189, in renderGraph
    plot_url_sold= graphSold(blob_sold))
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/templates/graph.html", line 5, in top-level template code
    <script src="{{ url_for('app/static',filename='styles/view.js') }}"></script>
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'app/static' with values ['filename']. Did you mean 'static' instead?
2019-10-08 08:19:19,942 - file - DEBUG - Reading blob: links.json
2019-10-08 08:19:21,167 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:19:23,236 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:19:23,547 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:19:23,833 - flask.app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./main.py", line 189, in renderGraph
    plot_url_sold= graphSold(blob_sold))
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/templates/graph.html", line 5, in top-level template code
    <script src="{{ url_for('',filename='styles/view.js') }}"></script>
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '' with values ['filename']. Did you mean 'static' instead?
2019-10-08 08:22:32,742 - file - DEBUG - Reading blob: links.json
2019-10-08 08:22:34,664 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:22:36,247 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:22:36,556 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:31:20,087 - file - DEBUG - Reading blob: links.json
2019-10-08 08:31:22,244 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:31:25,632 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:31:25,939 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:31:53,252 - file - DEBUG - Reading blob: links.json
2019-10-08 08:31:55,123 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:31:56,326 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:31:56,765 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:32:03,912 - file - DEBUG - Reading blob: links.json
2019-10-08 08:32:05,531 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:32:06,891 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:32:07,204 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:32:39,526 - file - DEBUG - Reading blob: links.json
2019-10-08 08:32:41,728 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:32:43,461 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:32:43,779 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:34:08,257 - file - DEBUG - Reading blob: links.json
2019-10-08 08:34:10,166 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:34:11,822 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:34:12,144 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:35:42,417 - file - DEBUG - Reading blob: links.json
2019-10-08 08:35:44,639 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:35:45,913 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:35:46,211 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:36:01,066 - file - DEBUG - Reading blob: links.json
2019-10-08 08:36:02,921 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:36:06,118 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:36:06,426 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:37:07,362 - file - DEBUG - Reading blob: links.json
2019-10-08 08:37:08,942 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:37:10,706 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:37:11,002 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:37:29,550 - file - DEBUG - Reading blob: links.json
2019-10-08 08:37:31,528 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:37:32,774 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:37:33,067 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:42:02,493 - file - DEBUG - Reading blob: links.json
2019-10-08 08:42:04,531 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:42:06,207 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:42:06,544 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:42:27,994 - file - DEBUG - Reading blob: links.json
2019-10-08 08:42:29,214 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:42:30,354 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:42:30,652 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:43:51,756 - file - DEBUG - Reading blob: links.json
2019-10-08 08:43:55,481 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:43:57,506 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:43:57,798 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:43:58,171 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 08:43:58,663 - file - DEBUG - Reading blob: visning.json
2019-10-08 08:44:04,658 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:44:06,610 - file - DEBUG - Filtering jsons..!!
2019-10-08 08:44:06,632 - file - DEBUG - Returning data...
2019-10-08 08:44:25,822 - file - DEBUG - Received date: 2019-10-09
2019-10-08 08:44:25,822 - file - DEBUG - Reading blob: visning.json
2019-10-08 08:44:30,801 - file - DEBUG - Filtering jsons..!!
2019-10-08 08:44:30,902 - file - DEBUG - Returning data...
2019-10-08 08:44:33,832 - file - DEBUG - Received date: 2019-10-17
2019-10-08 08:44:33,832 - file - DEBUG - Reading blob: visning.json
2019-10-08 08:44:41,903 - file - DEBUG - Filtering jsons..!!
2019-10-08 08:44:42,006 - file - DEBUG - Returning data...
2019-10-08 08:44:44,918 - file - DEBUG - Received date: 2019-10-25
2019-10-08 08:44:44,918 - file - DEBUG - Reading blob: visning.json
2019-10-08 08:44:52,078 - file - DEBUG - Filtering jsons..!!
2019-10-08 08:44:52,177 - file - DEBUG - Returning data...
2019-10-08 08:44:55,702 - file - DEBUG - Received date: 2019-10-30
2019-10-08 08:44:55,702 - file - DEBUG - Reading blob: visning.json
2019-10-08 08:45:00,758 - file - DEBUG - Filtering jsons..!!
2019-10-08 08:45:00,857 - file - DEBUG - Returning data...
2019-10-08 08:45:06,079 - file - DEBUG - Received date: 2019-10-28
2019-10-08 08:45:06,079 - file - DEBUG - Reading blob: visning.json
2019-10-08 08:45:12,877 - file - DEBUG - Filtering jsons..!!
2019-10-08 08:45:13,007 - file - DEBUG - Returning data...
2019-10-08 08:46:56,257 - file - DEBUG - Reading blob: links.json
2019-10-08 08:46:57,850 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:46:59,385 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:46:59,681 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 08:47:00,092 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 08:47:00,559 - file - DEBUG - Reading blob: visning.json
2019-10-08 08:47:08,279 - file - DEBUG - Reading blob: sold.json
2019-10-08 08:47:12,511 - file - DEBUG - Filtering jsons..!!
2019-10-08 08:47:12,568 - file - DEBUG - Returning data...
2019-10-08 09:08:25,034 - file - DEBUG - Reading blob: links.json
2019-10-08 09:08:27,143 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:08:29,628 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:08:29,986 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:08:30,464 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 09:08:31,276 - file - DEBUG - Reading blob: visning.json
2019-10-08 09:08:35,822 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:08:37,678 - file - DEBUG - Filtering jsons..!!
2019-10-08 09:08:37,745 - file - DEBUG - Returning data...
2019-10-08 09:13:26,811 - file - DEBUG - Reading blob: links.json
2019-10-08 09:13:28,547 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:13:30,646 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:13:31,005 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:13:31,353 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 09:13:32,099 - file - DEBUG - Reading blob: visning.json
2019-10-08 09:13:34,933 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:13:36,360 - file - DEBUG - Filtering jsons..!!
2019-10-08 09:13:36,382 - file - DEBUG - Returning data...
2019-10-08 09:18:05,753 - file - DEBUG - Reading blob: links.json
2019-10-08 09:18:07,802 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:18:09,307 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:18:09,592 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:18:09,911 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 09:18:10,393 - file - DEBUG - Reading blob: visning.json
2019-10-08 09:18:14,952 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:18:16,829 - file - DEBUG - Filtering jsons..!!
2019-10-08 09:18:16,852 - file - DEBUG - Returning data...
2019-10-08 09:26:25,125 - file - DEBUG - Reading blob: links.json
2019-10-08 09:26:27,217 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:26:28,984 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:26:29,323 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:26:29,656 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 09:26:30,145 - file - DEBUG - Reading blob: visning.json
2019-10-08 09:26:35,689 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:26:36,809 - file - DEBUG - Filtering jsons..!!
2019-10-08 09:26:36,832 - file - DEBUG - Returning data...
2019-10-08 09:31:57,388 - file - DEBUG - Reading blob: links.json
2019-10-08 09:31:59,443 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:32:02,314 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:32:02,610 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:32:02,940 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 09:32:03,413 - file - DEBUG - Reading blob: visning.json
2019-10-08 09:32:08,772 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:32:10,392 - file - DEBUG - Filtering jsons..!!
2019-10-08 09:32:10,415 - file - DEBUG - Returning data...
2019-10-08 09:35:11,681 - file - DEBUG - Reading blob: links.json
2019-10-08 09:35:14,055 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:35:15,295 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:35:15,588 - matplotlib.legend - WARNING - No handles with labels found to put in legend.
2019-10-08 09:35:15,932 - file - DEBUG - Reading blob: multiplePris.json
2019-10-08 09:35:16,411 - file - DEBUG - Reading blob: visning.json
2019-10-08 09:35:21,868 - file - DEBUG - Reading blob: sold.json
2019-10-08 09:35:23,297 - file - DEBUG - Filtering jsons..!!
2019-10-08 09:35:23,323 - file - DEBUG - Returning data...
